version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-1:769126752719:task-definition/ecs-nginx:1"
        LoadBalancerInfo:
          ContainerName: "ecs-nginx"
          ContainerPort: 80